apiVersion: v1
kind: Pod
metadata:
  name: gradle-pod
  namespace: jenkins
spec:
#   serviceAccountName: pecn-dev
  containers:
    - name: gradle
      image: gradle:7.2.0-jdk8
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "2048Mi"
          cpu: "500m"
      tty: true
      command:
        - cat
